# Generated by Django 3.0.2 on 2020-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
